.PHONY: help
help:
	@# Display usage.
	@./commonmake/usage Makefile

commnmake-sync:
	@# Sync commonmake
	@curl -L -o ./commonmake/usage

commnmake-remove:
	@# Remove commonmake
	@./commonmake/usage Makefile
