#! /usr/bin/env perl

use strict;
use warnings;

open (FILE, "./Makefile") or die "$!";
my $buf =  do { local $/; <FILE> };
close FILE;

while ($buf =~ /^([^._][a-zA-Z0-9_\-]*):(.*)\n(^\t\@\##.*\n)?((^\t\@\#.*\n)*)/gm ) {
    my $cmd = $1;
    my $synopsis = $3 || "";
    my $msg = $4 || "";

    $synopsis =~ s/@##//g;
    $synopsis =~ s/\A\s*(.*?)\s*\z/$1/;
    $msg =~ s/\t\@\#/ /g;
    printf("* %-20s\n%s\n", $cmd . " " . $synopsis, $msg);
}
